### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by ZARAEM** [SnuzzleWump/banner-text#3]
![image](https://github.com/SnuzzleWump/banner-text/assets/124304744/2ef2e79a-8f13-4530-b095-ef19a7a8e00d)

getting this

**Comment by SnuzzleWump** [comment]
hi, is this in singleplayer?

**Comment by ZARAEM** [comment]
> hi, is this in singleplayer?

In multi-player on spigot server

**Comment by SnuzzleWump** [comment]
I've tested it on a 1.21 spigot server and it works fine, I'm not sure what could be causing it but I'd guess it's a plugin, you could try a binary search:

1. Remove half of the existing things, and put them aside.
2. Run the program / game.
3. Does the issue still exist?
If YES: Repeat from step 1 with the current things.
IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
4. Repeat this process until the problematic thing/s have been found.

It could also be an issue with your client if you use mods, in which case you can do the same.

I hope this helps :)

**Comment by ZARAEM** [comment]
> I've tested it on a 1.21 spigot server and it works fine, I'm not sure what could be causing it but I'd guess it's a plugin, you could try a binary search:
> 
> 1. Remove half of the existing things, and put them aside.
> 2. Run the program / game.
> 3. Does the issue still exist?
>    If YES: Repeat from step 1 with the current things.
>    IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
> 4. Repeat this process until the problematic thing/s have been found.
> 
> It could also be an issue with your client if you use mods, in which case you can do the same.
> 
> I hope this helps :)

I'll try these, thanks for the detailed reply :)
